name: 02-pull-request-ci
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Request Message woww
        run: echo "wow pull_req ci is woirking"
      - name: WorkDIr
        run: pwd